# @package _global_
hydra:
  sweep:
    dir: ${data_path}/multieval
    subdir: ${run_id}
  run:
    dir: ${data_path}/eval/${run_id}

data_path: "./data"
run_id: "deepseek-v3_filepath"

defaults:
  - _self_
  - data_source: hf_eval
